// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var Bo, Pane;
  Pane = require('bo.pane');
  return Bo = (function() {
    Bo.prototype.panes = {};

    function Bo() {
      var element, pane, panes, _i, _len;
      panes = document.querySelectorAll('[data-bo-pane]');
      for (_i = 0, _len = panes.length; _i < _len; _i++) {
        element = panes[_i];
        pane = new Pane({
          element: element
        });
        this.panes[pane.id] = pane;
      }
      this.showFirst();
    }

    Bo.prototype.hideAll = function() {
      var id, pane, _ref, _results;
      _ref = this.panes;
      _results = [];
      for (id in _ref) {
        pane = _ref[id];
        _results.push(pane.hide());
      }
      return _results;
    };

    Bo.prototype.showFirst = function() {
      var id, pane, _ref, _results;
      _ref = this.panes;
      _results = [];
      for (id in _ref) {
        pane = _ref[id];
        pane.show();
        break;
      }
      return _results;
    };

    Bo.prototype.show = function(id) {
      this.hideAll();
      return this.panes[id].show();
    };

    return Bo;

  })();
});
