// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(function(require, exports, module) {
  var Bo, makeId, paneIdCounter;
  Bo = require('bo');
  paneIdCounter = 0;
  ({
    makePane: function(id) {
      var element;
      element = document.createElement('div');
      element.setAttribute('data-bo-pane', id);
      document.body.appendChild(element);
      return element;
    }
  });
  makeId = function() {
    return 'pane' + (++paneIdCounter);
  };
  return Bo.Pane = (function() {
    Pane.prototype.id = null;

    Pane.prototype.element = null;

    function Pane(options) {
      var element, html, idAttr;
      this.options = options;
      this.toggle = __bind(this.toggle, this);
      this.show = __bind(this.show, this);
      this.hide = __bind(this.hide, this);
      element = this.options.element;
      html = this.options.html;
      idAttr = element ? element.getAttribute('id') : void 0;
      this.id = this.options.id || idAttr || makeId();
      this.element = element || makePane(this.id);
      this.element.setAttribute('id', this.id);
      if (html) {
        this.element.innerHTML = html;
      }
    }

    Pane.prototype.hide = function() {
      return this.element.classList.remove('active');
    };

    Pane.prototype.show = function() {
      return this.element.classList.add('active');
    };

    Pane.prototype.toggle = function() {
      return this.element.classList.toggle('active');
    };

    return Pane;

  })();
});
