// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(function(require, exports, module) {
  var Bo, makeId, makePane, paneIdCounter;
  Bo = require('bo');
  paneIdCounter = 0;
  makePane = function(id) {
    var element;
    element = document.createElement('div');
    element.setAttribute('data-bo-pane', id);
    document.body.appendChild(element);
    return element;
  };
  makeId = function() {
    return 'pane' + (++paneIdCounter);
  };
  return Bo.Pane = (function() {
    Pane.prototype.id = null;

    Pane.prototype.element = null;

    function Pane(options) {
      var element, html, idAttr;
      this.options = options;
      this.clearAnimation = __bind(this.clearAnimation, this);
      element = this.options.element;
      html = this.options.html;
      idAttr = element ? element.getAttribute('data-bo-pane') : void 0;
      this.id = this.options.id || idAttr || makeId();
      this.element = element || makePane(this.id);
      this.element.setAttribute('data-bo-pane', this.id);
      if (html) {
        this.element.innerHTML = html;
      }
    }

    Pane.prototype.clearAnimation = function() {
      console.log('clear', this.element);
      return this.element.classList.remove('animate');
    };

    Pane.prototype.left = function() {
      console.log('left', this.element);
      this.element.classList.add('animate');
      this.element.classList.remove('right');
      this.element.classList.add('left');
      return setTimeout(this.clearAnimation, this.options.animationDuration);
    };

    Pane.prototype.right = function() {
      console.log('right', this.element, this.options.animationDuration);
      this.element.classList.add('animate');
      this.element.classList.remove('left');
      this.element.classList.add('right');
      return setTimeout(this.clearAnimation, this.options.animationDuration);
    };

    Pane.prototype.show = function() {
      console.log('show', this.element);
      this.element.classList.add('animate');
      this.element.classList.remove('left');
      this.element.classList.remove('right');
      return setTimeout(this.clearAnimation, this.options.animationDuration);
    };

    return Pane;

  })();
});
